const cleanPeople = [ { 
name: 'Luke Skywalker',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'C-3PO',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'R2-D2',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'Darth Vader',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'Leia Organa',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'Owen Lars',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'Beru Whitesun lars',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'R5-D4',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'Biggs Darklighter',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false },
{ name: 'Obi-Wan Kenobi',
species:  undefined ,
homeworld: undefined,
homeworldPopulation: undefined,
favorited: false } ]

export default cleanPeople;