export default cleanPeople = [ { name: 'Luke Skywalker',
species: [ 'https://swapi.co/api/species/1/' ],
homeworld: 'https://swapi.co/api/planets/1/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'C-3PO',
species: [ 'https://swapi.co/api/species/2/' ],
homeworld: 'https://swapi.co/api/planets/1/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'R2-D2',
species: [ 'https://swapi.co/api/species/2/' ],
homeworld: 'https://swapi.co/api/planets/8/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'Darth Vader',
species: [ 'https://swapi.co/api/species/1/' ],
homeworld: 'https://swapi.co/api/planets/1/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'Leia Organa',
species: [ 'https://swapi.co/api/species/1/' ],
homeworld: 'https://swapi.co/api/planets/2/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'Owen Lars',
species: [ 'https://swapi.co/api/species/1/' ],
homeworld: 'https://swapi.co/api/planets/1/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'Beru Whitesun lars',
species: [ 'https://swapi.co/api/species/1/' ],
homeworld: 'https://swapi.co/api/planets/1/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'R5-D4',
species: [ 'https://swapi.co/api/species/2/' ],
homeworld: 'https://swapi.co/api/planets/1/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'Biggs Darklighter',
species: [ 'https://swapi.co/api/species/1/' ],
homeworld: 'https://swapi.co/api/planets/1/',
homeworldPopulation: 'homeworld population',
favorited: false },
{ name: 'Obi-Wan Kenobi',
species: [ 'https://swapi.co/api/species/1/' ],
homeworld: 'https://swapi.co/api/planets/20/',
homeworldPopulation: 'homeworld population',
favorited: false } ]