const cleanPeople = [ { 
  name: 'Luke Skywalker',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'C-3PO',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'R2-D2',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'Darth Vader',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'Leia Organa',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'Owen Lars',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'Beru Whitesun lars',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'R5-D4',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'Biggs Darklighter',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false },
  { name: 'Obi-Wan Kenobi',
  species:  undefined ,
  homeworld: undefined,
  homeworldPopulation: undefined,
  favorited: false } 
];

const cleanPeopleWithValues = [{"favorited": false, "homeworld": "Tatooine", "homeworldPopulation": "200000", "name": "Luke Skywalker", "species": "Human"}, {"favorited": false, "homeworld": "Tatooine", "homeworldPopulation": "200000", "name": "C-3PO", "species": "Droid"}, {"favorited": false, "homeworld": "Naboo", "homeworldPopulation": "4500000000", "name": "R2-D2", "species": "Droid"}, {"favorited": false, "homeworld": "Tatooine", "homeworldPopulation": "200000", "name": "Darth Vader", "species": "Human"}, {"favorited": false, "homeworld": "Alderaan", "homeworldPopulation": "2000000000", "name": "Leia Organa", "species": "Human"}, {"favorited": false, "homeworld": "Tatooine", "homeworldPopulation": "200000", "name": "Owen Lars", "species": "Human"}, {"favorited": false, "homeworld": "Tatooine", "homeworldPopulation": "200000", "name": "Beru Whitesun lars", "species": "Human"}, {"favorited": false, "homeworld": "Tatooine", "homeworldPopulation": "200000", "name": "R5-D4", "species": "Droid"}, {"favorited": false, "homeworld": "Tatooine", "homeworldPopulation": "200000", "name": "Biggs Darklighter", "species": "Human"}, {"favorited": false, "homeworld": "Stewjon", "homeworldPopulation": "unknown", "name": "Obi-Wan Kenobi", "species": "Human"}]


export {cleanPeople, cleanPeopleWithValues};