export default cleanPlanets = [ { name: 'Alderaan',
terrain: 'grasslands, mountains',
population: '2000000000',
climate: 'temperate',
residents: 
 [ 'https://swapi.co/api/people/5/',
   'https://swapi.co/api/people/68/',
   'https://swapi.co/api/people/81/' ],
favorited: false },
{ name: 'Yavin IV',
terrain: 'jungle, rainforests',
population: '1000',
climate: 'temperate, tropical',
residents: [],
favorited: false },
{ name: 'Hoth',
terrain: 'tundra, ice caves, mountain ranges',
population: 'unknown',
climate: 'frozen',
residents: [],
favorited: false },
{ name: 'Dagobah',
terrain: 'swamp, jungles',
population: 'unknown',
climate: 'murky',
residents: [],
favorited: false },
{ name: 'Bespin',
terrain: 'gas giant',
population: '6000000',
climate: 'temperate',
residents: [ 'https://swapi.co/api/people/26/' ],
favorited: false },
{ name: 'Endor',
terrain: 'forests, mountains, lakes',
population: '30000000',
climate: 'temperate',
residents: [ 'https://swapi.co/api/people/30/' ],
favorited: false },
{ name: 'Naboo',
terrain: 'grassy hills, swamps, forests, mountains',
population: '4500000000',
climate: 'temperate',
residents: 
 [ 'https://swapi.co/api/people/3/',
   'https://swapi.co/api/people/21/',
   'https://swapi.co/api/people/36/',
   'https://swapi.co/api/people/37/',
   'https://swapi.co/api/people/38/',
   'https://swapi.co/api/people/39/',
   'https://swapi.co/api/people/42/',
   'https://swapi.co/api/people/60/',
   'https://swapi.co/api/people/61/',
   'https://swapi.co/api/people/66/',
   'https://swapi.co/api/people/35/' ],
favorited: false },
{ name: 'Coruscant',
terrain: 'cityscape, mountains',
population: '1000000000000',
climate: 'temperate',
residents: 
 [ 'https://swapi.co/api/people/34/',
   'https://swapi.co/api/people/55/',
   'https://swapi.co/api/people/74/' ],
favorited: false },
{ name: 'Kamino',
terrain: 'ocean',
population: '1000000000',
climate: 'temperate',
residents: 
 [ 'https://swapi.co/api/people/22/',
   'https://swapi.co/api/people/72/',
   'https://swapi.co/api/people/73/' ],
favorited: false },
{ name: 'Geonosis',
terrain: 'rock, desert, mountain, barren',
population: '100000000000',
climate: 'temperate, arid',
residents: [ 'https://swapi.co/api/people/63/' ],
favorited: false } ]