export default cleanVehicles = [ { name: 'Sand Crawler',
model: 'Digger Crawler',
vehicleClass: 'wheeled',
passengerCount: '30',
favorited: false },
{ name: 'T-16 skyhopper',
model: 'T-16 skyhopper',
vehicleClass: 'repulsorcraft',
passengerCount: '1',
favorited: false },
{ name: 'X-34 landspeeder',
model: 'X-34 landspeeder',
vehicleClass: 'repulsorcraft',
passengerCount: '1',
favorited: false },
{ name: 'TIE/LN starfighter',
model: 'Twin Ion Engine/Ln Starfighter',
vehicleClass: 'starfighter',
passengerCount: '0',
favorited: false },
{ name: 'Snowspeeder',
model: 't-47 airspeeder',
vehicleClass: 'airspeeder',
passengerCount: '0',
favorited: false },
{ name: 'TIE bomber',
model: 'TIE/sa bomber',
vehicleClass: 'space/planetary bomber',
passengerCount: '0',
favorited: false },
{ name: 'AT-AT',
model: 'All Terrain Armored Transport',
vehicleClass: 'assault walker',
passengerCount: '40',
favorited: false },
{ name: 'AT-ST',
model: 'All Terrain Scout Transport',
vehicleClass: 'walker',
passengerCount: '0',
favorited: false },
{ name: 'Storm IV Twin-Pod cloud car',
model: 'Storm IV Twin-Pod',
vehicleClass: 'repulsorcraft',
passengerCount: '0',
favorited: false },
{ name: 'Sail barge',
model: 'Modified Luxury Sail Barge',
vehicleClass: 'sail barge',
passengerCount: '500',
favorited: false } ]